# Generated by Django 4.1.5 on 2023-03-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_best_seller_bookinfo_collect_hot_search_usermodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collect',
            new_name='MyCollect',
        ),
    ]
